export const LOCATION = 'LOCATION';
export const CURRENT_WEATHER = 'CURRENT_WEATHER';
export const RAIN_PROPBABILITY = 'RAIN_PROBABILITY';
export const HUMIDITY = 'HUMIDITY';
export const TEMPERATURE = 'TEMPERATURE';
export const CATEGORIES = 'CATEGORIES';
export const CONDITION = 'CONDITION';
export const TOMORROW_WEATHER = 'TOMORROW_WEATHER';
