name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          REACT_APP_SERVER_API: ${{ secrets.REACT_APP_SERVER_API }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Delete to S3
        run: |
          aws s3 rm s3://raccoon-weather-client \
          --recursive \
          --exclude '*' \
          --include 'static/*' \
          --include 'index.html'

      - name: Upload to S3
        run: |
          aws s3 sync ./build s3://raccoon-weather-client \
          --exclude '*' \
          --include 'static/*' \
          --include 'index.html'

      - name: Cache Control Static
        run: |
          aws s3 cp s3://raccoon-weather-client s3://raccoon-weather-client \
          --recursive \
          --exclude "*" \
          --include 'static/*' --metadata-directive REPLACE --cache-control max-age=86400000,public

      - name: Invalidation Cloudfront
        run: aws cloudfront create-invalidation --distribution-id E3RJEBQJU11POG --paths '/*'
