name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: |
          aws s3 rm s3://prod-mes-grid --recursive --exclude '*' --include 'index.html' --include 'static/*' \
          aws s3 sync ./build s3://raccoon-weather-client --recursive --exclude '*' --include 'index.html' --include 'static/*' --acl public-read --cache-control max-age=86400000,public \
          aws s3 cp s3://raccoon-weather-client s3://raccoon-weather-client --recursive --exclude "*" --include "index.html" --metadata-directive REPLACE --acl public-read --cache-control max-age=0,must-revalidate,public --content-type "text/html; charset=utf-8" \

      - name: Purge CloudFront
        run: aws cloudfront create-invalidation --distribution-id E1TRNOGYS2XF84 --paths "/*"
